{{config(
	catalog = "hive",
	schema = "pm61devs3",
	materialized = "view"
)}}
WITH select_step1 as (
  SELECT
    "oracle"."CUSTOMER_DEMO"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ACTVTY_KEY" AS "SBSCRN_ACTVTY_KEY",
    "oracle"."CUSTOMER_DEMO"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ID" AS "SBSCRN_ID",
    "oracle"."CUSTOMER_DEMO"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",
    "oracle"."CUSTOMER_DEMO"."FACT_SUBSCRIPTION_ACTIVITY"."USED_ACTVTY_TYPE_ID" AS "USED_ACTVTY_TYPE_ID",
    "oracle"."CUSTOMER_DEMO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" AS "PLAN_ID"
  FROM
    "oracle"."CUSTOMER_DEMO"."FACT_SUBSCRIPTION_ACTIVITY"
),
join_step2 as (
  SELECT
    select_step1."SBSCRN_ACTVTY_KEY" AS "SBSCRN_ACTVTY_KEY",
    select_step1."SBSCRN_ID" AS "SBSCRN_ID",
    select_step1."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",
    select_step1."USED_ACTVTY_TYPE_ID" AS "USED_ACTVTY_TYPE_ID",
    select_step1."PLAN_ID" AS "PLAN_ID",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID1",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC"
  FROM
    select_step1
    LEFT OUTER JOIN "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES" ON (
      select_step1."SBSCRN_ACTVTY_KEY" = "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID"
      AND select_step1."PLAN_ID" = "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID"
    )
),
join_step3 as (
  SELECT
    join_step2."SBSCRN_ACTVTY_KEY" AS "SBSCRN_ACTVTY_KEY",
    join_step2."SBSCRN_ID" AS "SBSCRN_ID",
    join_step2."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",
    join_step2."USED_ACTVTY_TYPE_ID" AS "USED_ACTVTY_TYPE_ID",
    join_step2."PLAN_ID" AS "PLAN_ID",
    join_step2."PLAN_ID1" AS "PLAN_ID1",
    join_step2."PLAN_NAME" AS "PLAN_NAME",
    join_step2."DISC" AS "DISC",
    "oracle"."CUSTOMER_DEMO"."DIM_AGENT"."CSR_ID" AS "CSR_ID",
    "oracle"."CUSTOMER_DEMO"."DIM_AGENT"."AGENT_SUPERVISOR_RECORD_KEY" AS "AGENT_SUPERVISOR_RECORD_KEY",
    "oracle"."CUSTOMER_DEMO"."DIM_AGENT"."AGENT_SUPERVISOR_CSR_ID" AS "AGENT_SUPERVISOR_CSR_ID",
    "oracle"."CUSTOMER_DEMO"."DIM_AGENT"."AGENT_STATUS" AS "AGENT_STATUS",
    "oracle"."CUSTOMER_DEMO"."DIM_AGENT"."AGENT_ROLE_START_DATE" AS "AGENT_ROLE_START_DATE"
  FROM
    join_step2
    INNER JOIN "oracle"."CUSTOMER_DEMO"."DIM_AGENT" ON (
      join_step2."PLAN_NAME" != "oracle"."CUSTOMER_DEMO"."DIM_AGENT"."CSR_ID"
    )
)
SELECT
  *
FROM
  join_step3
LIMIT
  100