{{config(
	schema = "DATA_PIPELINE",
	materialized = "view"
)}}
WITH select_step1 as (
  SELECT
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."TLOG_SALE_HEADER_UID" AS "TLOG_SALE_HEADER_UID",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."REST_KEY" AS "REST_KEY",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."DATE_KEY" AS "DATE_KEY",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."SEMS_TLOG_SALE_HEADERS_UID" AS "SEMS_TLOG_SALE_HEADERS_UID",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."REST_NO" AS "REST_NO",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ORDER_NUMBER" AS "ORDER_NUMBER",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ORDER_SUB_TOTAL" AS "ORDER_SUB_TOTAL",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."NOTAX" AS "NOTAX",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."REFUND" AS "REFUND",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."CREATED_DT" AS "CREATED_DT",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."LOAD_ID" AS "LOAD_ID",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."PARTITION_DATE_KEY" AS "PARTITION_DATE_KEY",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."REST_NO1" AS "REST_NO1",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."REST_NM" AS "REST_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OWNERSHIP_CD" AS "OWNERSHIP_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."STATUS_CD" AS "STATUS_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ADI_NO" AS "ADI_NO",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ADI_NM" AS "ADI_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."CITY_NM" AS "CITY_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."STATE_ID" AS "STATE_ID",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."STATE_NM" AS "STATE_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."COUNTY_ID" AS "COUNTY_ID",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."COUNTY_NM" AS "COUNTY_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."COUNTRY_ID" AS "COUNTRY_ID",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."COUNTRY_NM" AS "COUNTRY_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."POSTAL_CD" AS "POSTAL_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."PHONE_NO" AS "PHONE_NO",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."LOCATION_GRP_CD" AS "LOCATION_GRP_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ARCH_GRP_CD" AS "ARCH_GRP_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ARCH_GRP_CD_NM" AS "ARCH_GRP_CD_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ARCH_CD" AS "ARCH_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ARCH_CD_NM" AS "ARCH_CD_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."DRIVE_THRU_CD" AS "DRIVE_THRU_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."DRIVE_THRU_CD_NM" AS "DRIVE_THRU_CD_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."PLAYGRND_CD" AS "PLAYGRND_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."PLAYGRND_CD_NM" AS "PLAYGRND_CD_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."KITCHEN_CD" AS "KITCHEN_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."KITCHEN_CD_NM" AS "KITCHEN_CD_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."DINING_RM_CD" AS "DINING_RM_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."DINING_RM_CD_NM" AS "DINING_RM_CD_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."REPORTED_CRNCY" AS "REPORTED_CRNCY",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."FRANCHISEE_GRP_NO" AS "FRANCHISEE_GRP_NO",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."FRANCHISEE_GRP_NM" AS "FRANCHISEE_GRP_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPER_NO" AS "OPER_NO",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPS_AREA_NM" AS "OPS_AREA_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPS_MRKT_NM" AS "OPS_MRKT_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPS_DIST_NM" AS "OPS_DIST_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPS_DIV_NM" AS "OPS_DIV_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPS_ZN_NM" AS "OPS_ZN_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."OPS_GTEAM_NM" AS "OPS_GTEAM_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."SEAT_CNT" AS "SEAT_CNT",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."ROYALTY_PCT" AS "ROYALTY_PCT",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."FRAN_AGMT_EXP_DT" AS "FRAN_AGMT_EXP_DT",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."LOC_CD" AS "LOC_CD",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."CODE_SHORT_NM" AS "CODE_SHORT_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."DATA_PROVIDER" AS "DATA_PROVIDER",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."FRAN_ROLLUP_NM" AS "FRAN_ROLLUP_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."FRAN_GRP_RELATIONSHIP" AS "FRAN_GRP_RELATIONSHIP",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."EXTERIOR_IMAGE_NM" AS "EXTERIOR_IMAGE_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."BUILDING_PROTOTYPE_NM" AS "BUILDING_PROTOTYPE_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."LOC_TYPE_NM" AS "LOC_TYPE_NM",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."INT_REST_NAME" AS "INT_REST_NAME",
    "SCHEMA_INFO"."RESTAURANT_ORDERS"."HOME_DLVRY" AS "HOME_DLVRY"
  FROM
    "SCHEMA_INFO"."RESTAURANT_ORDERS"
  WHERE
    (
      "SCHEMA_INFO"."RESTAURANT_ORDERS"."TLOG_SALE_HEADER_UID" IS NOT NULL
    )
),
join_step2 as (
  SELECT
    select_step1."TLOG_SALE_HEADER_UID" AS "TLOG_SALE_HEADER_UID",
    select_step1."REST_KEY" AS "REST_KEY",
    select_step1."DATE_KEY" AS "DATE_KEY",
    select_step1."SEMS_TLOG_SALE_HEADERS_UID" AS "SEMS_TLOG_SALE_HEADERS_UID",
    select_step1."REST_NO" AS "REST_NO",
    select_step1."ORDER_NUMBER" AS "ORDER_NUMBER",
    select_step1."ORDER_SUB_TOTAL" AS "ORDER_SUB_TOTAL",
    select_step1."NOTAX" AS "NOTAX",
    select_step1."REFUND" AS "REFUND",
    select_step1."CREATED_DT" AS "CREATED_DT",
    select_step1."LOAD_ID" AS "LOAD_ID",
    select_step1."PARTITION_DATE_KEY" AS "PARTITION_DATE_KEY",
    select_step1."REST_NO1" AS "REST_NO1",
    select_step1."REST_NM" AS "REST_NM",
    select_step1."OWNERSHIP_CD" AS "OWNERSHIP_CD",
    select_step1."STATUS_CD" AS "STATUS_CD",
    select_step1."ADI_NO" AS "ADI_NO",
    select_step1."ADI_NM" AS "ADI_NM",
    select_step1."CITY_NM" AS "CITY_NM",
    select_step1."STATE_ID" AS "STATE_ID",
    select_step1."STATE_NM" AS "STATE_NM",
    select_step1."COUNTY_ID" AS "COUNTY_ID",
    select_step1."COUNTY_NM" AS "COUNTY_NM",
    select_step1."COUNTRY_ID" AS "COUNTRY_ID",
    select_step1."COUNTRY_NM" AS "COUNTRY_NM",
    select_step1."POSTAL_CD" AS "POSTAL_CD",
    select_step1."PHONE_NO" AS "PHONE_NO",
    select_step1."LOCATION_GRP_CD" AS "LOCATION_GRP_CD",
    select_step1."ARCH_GRP_CD" AS "ARCH_GRP_CD",
    select_step1."ARCH_GRP_CD_NM" AS "ARCH_GRP_CD_NM",
    select_step1."ARCH_CD" AS "ARCH_CD",
    select_step1."ARCH_CD_NM" AS "ARCH_CD_NM",
    select_step1."DRIVE_THRU_CD" AS "DRIVE_THRU_CD",
    select_step1."DRIVE_THRU_CD_NM" AS "DRIVE_THRU_CD_NM",
    select_step1."PLAYGRND_CD" AS "PLAYGRND_CD",
    select_step1."PLAYGRND_CD_NM" AS "PLAYGRND_CD_NM",
    select_step1."KITCHEN_CD" AS "KITCHEN_CD",
    select_step1."KITCHEN_CD_NM" AS "KITCHEN_CD_NM",
    select_step1."DINING_RM_CD" AS "DINING_RM_CD",
    select_step1."DINING_RM_CD_NM" AS "DINING_RM_CD_NM",
    select_step1."REPORTED_CRNCY" AS "REPORTED_CRNCY",
    select_step1."FRANCHISEE_GRP_NO" AS "FRANCHISEE_GRP_NO",
    select_step1."FRANCHISEE_GRP_NM" AS "FRANCHISEE_GRP_NM",
    select_step1."OPER_NO" AS "OPER_NO",
    select_step1."OPS_AREA_NM" AS "OPS_AREA_NM",
    select_step1."OPS_MRKT_NM" AS "OPS_MRKT_NM",
    select_step1."OPS_DIST_NM" AS "OPS_DIST_NM",
    select_step1."OPS_DIV_NM" AS "OPS_DIV_NM",
    select_step1."OPS_ZN_NM" AS "OPS_ZN_NM",
    select_step1."OPS_GTEAM_NM" AS "OPS_GTEAM_NM",
    select_step1."SEAT_CNT" AS "SEAT_CNT",
    select_step1."ROYALTY_PCT" AS "ROYALTY_PCT",
    select_step1."FRAN_AGMT_EXP_DT" AS "FRAN_AGMT_EXP_DT",
    select_step1."LOC_CD" AS "LOC_CD",
    select_step1."CODE_SHORT_NM" AS "CODE_SHORT_NM",
    select_step1."DATA_PROVIDER" AS "DATA_PROVIDER",
    select_step1."FRAN_ROLLUP_NM" AS "FRAN_ROLLUP_NM",
    select_step1."FRAN_GRP_RELATIONSHIP" AS "FRAN_GRP_RELATIONSHIP",
    select_step1."EXTERIOR_IMAGE_NM" AS "EXTERIOR_IMAGE_NM",
    select_step1."BUILDING_PROTOTYPE_NM" AS "BUILDING_PROTOTYPE_NM",
    select_step1."LOC_TYPE_NM" AS "LOC_TYPE_NM",
    select_step1."INT_REST_NAME" AS "INT_REST_NAME",
    select_step1."HOME_DLVRY" AS "HOME_DLVRY",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."MER" AS "MER",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."LEN" AS "LEN",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."ROLLUP1" AS "ROLLUP1",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."ASP" AS "ASP",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."STARTDATE" AS "STARTDATE",
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."ENDDATE" AS "ENDDATE"
  FROM
    select_step1
    LEFT OUTER JOIN "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES" ON (
      select_step1."REST_KEY" != "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID"
    )
),
group_by_step3 as (
  SELECT
    CAST(join_step2."REST_KEY" as INT) AS "REST_KEY_GB",
    CAST(Count("ORDER_SUB_TOTAL") as INT) AS "Count of ORDER_SUB_TOTAL_GB_SUM"
  FROM
    join_step2
  GROUP BY
    join_step2."REST_KEY"
),
order_by_step4 as (
  SELECT
    *
  FROM
    group_by_step3
  ORDER BY
    group_by_step3."Count of ORDER_SUB_TOTAL_GB_SUM" ASC
)
SELECT
  *
FROM
  order_by_step4
LIMIT
  100