{{config(
	catalog = "redshift_dev",
	schema = "public",
	materialized = "table"
)}}
WITH select_step1 as (
  SELECT
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."MER" AS "REVENUE",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."LEN" AS "LEN",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."ROLLUP1" AS "ROLLUP1",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."ASP" AS "ASP",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."STARTDATE" AS "STARTDATE",
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"."ENDDATE" AS "ENDDATE",
    CAST(UPPER("PLAN_NAME") AS varchar) AS "UPPER_PLAN_NAME"
  FROM
    "oracle"."CUSTOMER_DEMO"."MASTER_PLAN_TABLE_WDATES"
),
join_step2 as (
  SELECT
    select_step1."PLAN_ID" AS "PLAN_ID",
    select_step1."PLAN_NAME" AS "PLAN_NAME",
    select_step1."REVENUE" AS "REVENUE",
    select_step1."DISC" AS "DISC",
    select_step1."PACKAGE" AS "PACKAGE",
    select_step1."LEN" AS "LEN",
    select_step1."ROLLUP1" AS "ROLLUP1",
    select_step1."ASP" AS "ASP",
    select_step1."STARTDATE" AS "STARTDATE",
    select_step1."ENDDATE" AS "ENDDATE",
    select_step1."UPPER_PLAN_NAME" AS "UPPER_PLAN_NAME",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ACTVTY_KEY" AS "SBSCRN_ACTVTY_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ID" AS "SBSCRN_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."USED_ACTVTY_TYPE_ID" AS "USED_ACTVTY_TYPE_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_DT" AS "ACTVTY_DT",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TS" AS "ACTVTY_TS",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."HHLD_ID" AS "HHLD_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PRTY_KEY" AS "PRTY_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PRTY_ID" AS "PRTY_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_KEY" AS "PARNT_ACCT_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_ID" AS "PARNT_ACCT_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_NUM" AS "PARNT_ACCT_NUM",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."CHILD_ACCT_KEY" AS "CHILD_ACCT_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."CHILD_ACCT_ID" AS "CHILD_ACCT_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."CHILD_ACCT_NUM" AS "CHILD_ACCT_NUM",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."VEH_KEY" AS "VEH_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."DVC_KEY" AS "DVC_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."dvc_id" AS "dvc_id",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."EQMNT_KEY" AS "EQMNT_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."EQMNT_ID" AS "EQMNT_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_KEY" AS "PLAN_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" AS "PLAN_ID1",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."OFR_ID" AS "OFR_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_KEY" AS "FROM_PLAN_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_ID" AS "FROM_PLAN_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_OFR_ID" AS "FROM_OFR_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PROD_KEY" AS "PROD_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PROD_ID" AS "PROD_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PROD_KEY" AS "FROM_PROD_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PROD_ID" AS "FROM_PROD_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PKG_ID" AS "PKG_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PKG_ID" AS "FROM_PKG_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FEAT_ID" AS "FEAT_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."AGN_KEY" AS "AGN_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."cust_rep_id" AS "cust_rep_id",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PTNR_ID" AS "PTNR_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."LNKD_INET_FL" AS "LNKD_INET_FL",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."MRD_TYPE_CD" AS "MRD_TYPE_CD",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCR_LIFCYC_KEY" AS "SBSCR_LIFCYC_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."CONV_REP_OWN_SEGMT_KEY" AS "CONV_REP_OWN_SEGMT_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."OWNR_TYPE2_KEY" AS "OWNR_TYPE2_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."DEACTIVATION_REASON_CODE" AS "DEACTIVATION_REASON_CODE",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."TRIAL_ID" AS "TRIAL_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SRVC_ID" AS "SRVC_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."RENW_ID" AS "RENW_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_RENW_ID" AS "FROM_RENW_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."COLL_SCNRO_ID" AS "COLL_SCNRO_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SRVC_LVL_PMT_KEY" AS "SRVC_LVL_PMT_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."NONPAY_SRVC_KEY" AS "NONPAY_SRVC_KEY",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."BILLING_METHOD" AS "BILLING_METHOD",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_BILLING_METHOD" AS "FROM_BILLING_METHOD",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SLFPAY_TURNOVER_RSN" AS "SLFPAY_TURNOVER_RSN",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SLFPAY_TURNOVER_DT" AS "SLFPAY_TURNOVER_DT",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."FUTURE_DEACTVN_DT" AS "FUTURE_DEACTVN_DT",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."SCHD_SEASONAL_SUSP_REACTVN_DT" AS "SCHD_SEASONAL_SUSP_REACTVN_DT",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."Call_Reason" AS "Call_Reason",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."Call_Disposition" AS "Call_Disposition",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."INSE_USER_ID" AS "INSE_USER_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."INSE_TS" AS "INSE_TS",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."UPDT_USER_ID" AS "UPDT_USER_ID",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."UPDT_TS" AS "UPDT_TS",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."Save_Activity" AS "Save_Activity",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."Deact_Activity_By_Save_Agent" AS "Deact_Activity_By_Save_Agent",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."Conversion_Activity_By_Save_Agent" AS "Conversion_Activity_By_Save_Agent",
    "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."Save_Opportunity_Activity" AS "Save_Opportunity_Activity"
  FROM
    select_step1
    LEFT OUTER JOIN "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY" ON (
      select_step1."PLAN_ID" = "mysql_galaxy"."customer_demo"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID"
    )
),
join_step3 as (
  SELECT
    join_step2."PLAN_ID" AS "PLAN_ID",
    join_step2."PLAN_NAME" AS "PLAN_NAME",
    join_step2."REVENUE" AS "REVENUE",
    join_step2."DISC" AS "DISC",
    join_step2."PACKAGE" AS "PACKAGE",
    join_step2."LEN" AS "LEN",
    join_step2."ROLLUP1" AS "ROLLUP1",
    join_step2."ASP" AS "ASP",
    join_step2."STARTDATE" AS "STARTDATE",
    join_step2."ENDDATE" AS "ENDDATE",
    join_step2."UPPER_PLAN_NAME" AS "UPPER_PLAN_NAME",
    join_step2."SBSCRN_ACTVTY_KEY" AS "SBSCRN_ACTVTY_KEY",
    join_step2."SBSCRN_ID" AS "SBSCRN_ID",
    join_step2."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",
    join_step2."USED_ACTVTY_TYPE_ID" AS "USED_ACTVTY_TYPE_ID",
    join_step2."ACTVTY_DT" AS "ACTVTY_DT",
    join_step2."ACTVTY_TS" AS "ACTVTY_TS",
    join_step2."HHLD_ID" AS "HHLD_ID",
    join_step2."PRTY_KEY" AS "PRTY_KEY",
    join_step2."PRTY_ID" AS "PRTY_ID",
    join_step2."PARNT_ACCT_KEY" AS "PARNT_ACCT_KEY",
    join_step2."PARNT_ACCT_ID" AS "PARNT_ACCT_ID",
    join_step2."PARNT_ACCT_NUM" AS "PARNT_ACCT_NUM",
    join_step2."CHILD_ACCT_KEY" AS "CHILD_ACCT_KEY",
    join_step2."CHILD_ACCT_ID" AS "CHILD_ACCT_ID",
    join_step2."CHILD_ACCT_NUM" AS "CHILD_ACCT_NUM",
    join_step2."VEH_KEY" AS "VEH_KEY",
    join_step2."DVC_KEY" AS "DVC_KEY",
    join_step2."dvc_id" AS "dvc_id",
    join_step2."EQMNT_KEY" AS "EQMNT_KEY",
    join_step2."EQMNT_ID" AS "EQMNT_ID",
    join_step2."PLAN_KEY" AS "PLAN_KEY",
    join_step2."PLAN_ID1" AS "PLAN_ID1",
    join_step2."OFR_ID" AS "OFR_ID",
    join_step2."FROM_PLAN_KEY" AS "FROM_PLAN_KEY",
    join_step2."FROM_PLAN_ID" AS "FROM_PLAN_ID",
    join_step2."FROM_OFR_ID" AS "FROM_OFR_ID",
    join_step2."PROD_KEY" AS "PROD_KEY",
    join_step2."PROD_ID" AS "PROD_ID",
    join_step2."FROM_PROD_KEY" AS "FROM_PROD_KEY",
    join_step2."FROM_PROD_ID" AS "FROM_PROD_ID",
    join_step2."PKG_ID" AS "PKG_ID",
    join_step2."FROM_PKG_ID" AS "FROM_PKG_ID",
    join_step2."FEAT_ID" AS "FEAT_ID",
    join_step2."AGN_KEY" AS "AGN_KEY",
    join_step2."cust_rep_id" AS "cust_rep_id",
    join_step2."PTNR_ID" AS "PTNR_ID",
    join_step2."LNKD_INET_FL" AS "LNKD_INET_FL",
    join_step2."MRD_TYPE_CD" AS "MRD_TYPE_CD",
    join_step2."SBSCR_LIFCYC_KEY" AS "SBSCR_LIFCYC_KEY",
    join_step2."CONV_REP_OWN_SEGMT_KEY" AS "CONV_REP_OWN_SEGMT_KEY",
    join_step2."OWNR_TYPE2_KEY" AS "OWNR_TYPE2_KEY",
    join_step2."DEACTIVATION_REASON_CODE" AS "DEACTIVATION_REASON_CODE",
    join_step2."TRIAL_ID" AS "TRIAL_ID",
    join_step2."SRVC_ID" AS "SRVC_ID",
    join_step2."RENW_ID" AS "RENW_ID",
    join_step2."FROM_RENW_ID" AS "FROM_RENW_ID",
    join_step2."COLL_SCNRO_ID" AS "COLL_SCNRO_ID",
    join_step2."SRVC_LVL_PMT_KEY" AS "SRVC_LVL_PMT_KEY",
    join_step2."NONPAY_SRVC_KEY" AS "NONPAY_SRVC_KEY",
    join_step2."BILLING_METHOD" AS "BILLING_METHOD",
    join_step2."FROM_BILLING_METHOD" AS "FROM_BILLING_METHOD",
    join_step2."SLFPAY_TURNOVER_RSN" AS "SLFPAY_TURNOVER_RSN",
    join_step2."SLFPAY_TURNOVER_DT" AS "SLFPAY_TURNOVER_DT",
    join_step2."FUTURE_DEACTVN_DT" AS "FUTURE_DEACTVN_DT",
    join_step2."SCHD_SEASONAL_SUSP_REACTVN_DT" AS "SCHD_SEASONAL_SUSP_REACTVN_DT",
    join_step2."Call_Reason" AS "Call_Reason",
    join_step2."Call_Disposition" AS "Call_Disposition",
    join_step2."INSE_USER_ID" AS "INSE_USER_ID",
    join_step2."INSE_TS" AS "INSE_TS",
    join_step2."UPDT_USER_ID" AS "UPDT_USER_ID",
    join_step2."UPDT_TS" AS "UPDT_TS",
    join_step2."Save_Activity" AS "Save_Activity",
    join_step2."Deact_Activity_By_Save_Agent" AS "Deact_Activity_By_Save_Agent",
    join_step2."Conversion_Activity_By_Save_Agent" AS "Conversion_Activity_By_Save_Agent",
    join_step2."Save_Opportunity_Activity" AS "Save_Opportunity_Activity",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_RECORD_KEY" AS "AGENT_RECORD_KEY",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_ID" AS "AGENT_ID",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."CSR_ID" AS "CSR_ID",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_SUPERVISOR_RECORD_KEY" AS "AGENT_SUPERVISOR_RECORD_KEY",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_SUPERVISOR_CSR_ID" AS "AGENT_SUPERVISOR_CSR_ID",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_STATUS" AS "AGENT_STATUS",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_ROLE_START_DATE" AS "AGENT_ROLE_START_DATE",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_ROLE_END_DATE" AS "AGENT_ROLE_END_DATE",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_ROLE_SMS" AS "AGENT_ROLE_SMS",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_ROLE_MARKETING" AS "AGENT_ROLE_MARKETING",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_LOCATION" AS "AGENT_LOCATION",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_VENDOR" AS "AGENT_VENDOR",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_SITE" AS "AGENT_SITE",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_LOB" AS "AGENT_LOB",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."ACTIVATION_SOURCE" AS "ACTIVATION_SOURCE",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."CURRENT_RECORD_FLAG" AS "CURRENT_RECORD_FLAG",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."DELETED_RECORD_FLAG" AS "DELETED_RECORD_FLAG",
    "snowflake"."SCHEMA_INFO"."DIM_AGENT"."COLUMN17" AS "COLUMN17"
  FROM
    join_step2
    LEFT OUTER JOIN "snowflake"."SCHEMA_INFO"."DIM_AGENT" ON (
      join_step2."AGN_KEY" = "snowflake"."SCHEMA_INFO"."DIM_AGENT"."AGENT_RECORD_KEY"
    )
)
SELECT
  *
FROM
  join_step3
LIMIT
  100